# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{piglop-ovh-rb}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Witrant", "Aur\303\251lien AMILIN"]
  s.date = %q{2010-10-10}
  s.email = %q{mike@lepton.fr}
  s.executables = ["ovhrb", "failover_check"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/failover_check",
     "bin/ovhrb",
     "lib/ovh-rb.rb",
     "lib/ovhrb/config.rb",
     "lib/ovhrb/converter.rb",
     "lib/ovhrb/core_additions.rb",
     "lib/ovhrb/manager/manager.rb",
     "lib/ovhrb/manager/managerDriver.rb",
     "lib/ovhrb/manager/managerServiceClient.rb",
     "lib/ovhrb/ovh_object.rb",
     "lib/ovhrb/session.rb",
     "lib/ovhrb/soap_request_handler.rb",
     "ovhrb.yml.sample"
  ]
  s.homepage = %q{http://github.com/piglop/ovh-rb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{ovh-rb helps you to use the OVH SOAPI in a ruby way}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

